export const TYPE = {
  CREATE_DATA: "CREATE_DATE",
  READ_ALL_DATA: "READ_ALL_DATE",
  READ_ON_DATA: "READ_ON_DATE",
  UPDATE_DATA: "UPDATE_DATE",
  DELETE_DATA: "DELETE_DATA",
  NO_DATA: "NO_DATA",
};
